### ISSUE TITLE
Issue with Special Characters in File Names When Downloading and Converting Videos

### ISSUE THREAD

**Issue by REUBATCODE** [REUBATCODE/pythonMp3#1]
Problem Description:
When using the download and conversion feature to MP3 format, it has been observed that if the video title contains special characters (such as question marks, quotes, non-ASCII characters, etc.), the process fails when attempting to save the MP3 file. This is due to these characters not being valid in file names on certain file systems, such as Windows.

Steps to Reproduce:
Attempt to download a video whose title contains special characters, for example, "¿Por qué no me comprendes?".
Notice that the process fails when trying to save the MP3 file, with an error message related to "invalid argument".

Proposed Solution:
Implement a file name cleaning function that removes or replaces special characters before saving the MP3 file. Here is an example of how this function could be implemented:

```bash
import re

def clean_filename(title):
    """
    Cleans the video title to ensure it's a valid file name.
    Removes special characters and replaces spaces with underscores.
    """
    cleaned_title = re.sub(r'[\\/*?:"<>|\']', '', title)
    cleaned_title = re.sub(r'\s+', '_', cleaned_title)  # Replace spaces with underscores
    return cleaned_title
```

**Comment by hrantvirabyan** [comment]
hey did you happen to solve this?

**Comment by REUBATCODE** [comment]
> hey did you happen to solve this?

Hey @hrantvirabyan , I didn't see your comment, sorry for that. But yes, this function solved the problem.
